<a href="https://colab.research.google.com/github/TejashreeDV/Atharvo-final-project/blob/main/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#!pip install pandas
import pandas as pd

In [ ]:
d = {"college":[34, 123, 65, 12, 431], "University":[23, 45, 65, 1, 67]}

In [ ]:
df = pd.DataFrame(d)
df

   college  University
0       34          23
1      123          45
2       65          65
3       12           1
4      431          67

In [ ]:
type(df)

pandas.core.frame.DataFrame

In [ ]:
df["University"]

0    23
1    45
2    65
3     1
4    67
Name: University, dtype: int64

In [ ]:
df.loc[3]

college       12
University     1
Name: 3, dtype: int64

In [ ]:
df.iloc[]

SyntaxError: invalid syntax (<ipython-input-98-75d2b8f5a532>, line 1)

In [ ]:
df.index = ["a",  "b", "c", "d", "e"]

In [ ]:
df

   college  University
a       34          23
b      123          45
c       65          65
d       12           1
e      431          67

In [ ]:
df.loc["d"]

college       12
University     1
Name: d, dtype: int64

In [ ]:
df.iloc[3]

college       12
University     1
Name: d, dtype: int64

In [ ]:
l = [[1, 2, 3], [4, 5,  6]]

In [ ]:
df2= pd.DataFrame(l,  columns = ["X",  "Y", "Z"], index = [101,  102])
df2

     X  Y  Z
101  1  2  3
102  4  5  6

In [ ]:
df2.columns = ['A', "b",  "c"]

In [ ]:
df2

   A  b  c
0  1  2  3
1  4  5  6

In [ ]:
df3 = pd.DataFrame()

In [ ]:
df3

Empty DataFrame
Columns: []
Index: []

In [ ]:
df3["Column1"] = [122, 234, 345, 456, 67, 8, 9]

In [ ]:
df3["column2"] = [23, 24, 56, 23, 34,  10, 12]

In [ ]:
df3

   Column1  column2
0      122       23
1      234       24
2      345       56
3      456       23
4       67       34
5        8       10
6        9       12

In [ ]:
df3["column2"] = [12, 0, 0, 0, 0,  0,  0]

In [ ]:
df3

   Column1  column2
0      122       12
1      234        0
2      345        0
3      456        0
4       67        0
5        8        0
6        9        0

In [ ]:
df3.loc[8] = [23, 90]

In [ ]:
df3

   Column1  column2
0      122       12
1      234        0
2      345        0
3      456        0
4       67        0
5        8        0
6        9        0
8       23       90

In [ ]:
df3.drop("Column1", axis = 1, inplace = True)

In [ ]:
df3

   column2
0       12
1        0
2        0
3        0
4        0
5        0
6        0
8       90

In [ ]:
df.drop(8, axis = 0, inplace = True)

KeyError: '[8] not found in axis'

In [ ]:
df

   college  University
a       34          23
b      123          45
c       65          65
d       12           1
e      431          67

In [ ]:
df.to_dict()

{'college': {'a': 34, 'b': 123, 'c': 65, 'd': 12, 'e': 431},
 'University': {'a': 23, 'b': 45, 'c': 65, 'd': 1, 'e': 67}}

In [ ]:
df.to_json("newjson.json")

In [ ]:
df.sort_index()

   college  University
a       34          23
b      123          45
c       65          65
d       12           1
e      431          67

In [ ]:
df.sort_values(by = "University")

   college  University
d       12           1
a       34          23
b      123          45
c       65          65
e      431          67

In [ ]:
df.reset_index()

  index  college  University
0     a       34          23
1     b      123          45
2     c       65          65
3     d       12           1
4     e      431          67

In [ ]:
df

   college  University
0       34          23
1      123          45
2       65          65
3       12           1
4      431          67

In [ ]:
pd.read_